EndGame/EndGame/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]

EndGame/mainapp/urls.py
from django.urls import path, re_path
from . import views

app_name = 'mainapp'
urlpatterns = [
    path("", views.index, name='index'),
    path("dashboard",views.dashboard, name="dashboard"),
    path("login",views.login,name="login"),
    path("mycustomers",views.myCustomers, name="myCustomers"),
    path("searchDetails",views.searchDetails, name="searchDetails"),
    path("logout",views.logout,name="logout"),
    path("sendEmail",views.sendEmail,name="sendEmail"),
    #getting ss of link.
    path("grabPhoto", views.grabPhoto, name="grabPhoto"),
    #mycustomers/pk
    re_path(r'^(?P<pk>[0-9]+)/$', views.customerDetail, name="customerDetail"),

]

EndGame/mainapp/models.py
from django.db import models
import pymongo
import base64
# Create your models here.

class CustomerDatabase:
    def __init__(self):
        self.client = pymongo.MongoClient("mongodb://jd254:pass123@cluster0-shard-00-00-yftzb.mongodb.net:27017,cluster0-shard-00-01-yftzb.mongodb.net:27017,cluster0-shard-00-02-yftzb.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true")
        self.mydb = self.client["customer"]

    def getData(self):
        mycol = self.mydb["data"]
        res = []
        for x in mycol.find({},{"_id": 0,"address":0}):
            res.append(x)
        return res

    def getDataFromPk(self,pk):
        mycol=self.mydb["data"]
        x=mycol.find_one({"pk":pk},{"_id": 0,"address":0})
        if x == None:
            return False
        else:
            return x

    def setImage(self,path,pk):
        mycol = self.mydb["data"]
        with open(path, "rb") as imageFile:
            str = base64.b64encode(imageFile.read())
            mycol.update_one({"pk":pk},{"$set":{"image":str}})




    def getImage(self,uname):
        mycol = self.mydb["data"]
        res=mycol.find_one({"name":uname})
        fh = open("test.jpg", "wb")
        fh.write(base64.b64decode(res["image"]))
        fh.close()
        return "test.jpg"


    def insertData(self,name,phoneNumber,email,dateOfBirth,gender,password,location=None,policyNumber=None,cliendID=None):
        mycol = self.mydb["data"]
        if mycol.find_one({"email":email})==None:
            x = mycol.insert_one({"name":name,"phoneNumber":phoneNumber,"email":email,"dateOfBirth":dateOfBirth,"gender":gender,"password":password,"location":location,"policyNumber":policyNumber,"cliendID":cliendID})
            return True
        else:
            return False

    '''
    def insertHistory(self,email,time):
        mycol = self.mydb["history"]
        if mycol.find_one({"email":email})==None:
            x=mycol.insert_one({"email":email,"log":[]})
        log=mycol.find_one({"email": email})['log']
        log.insert(0,time)
        mycol.update_one({"email": email}, {"$set": {"log": log}})

    def deleteData(self,email):
        mycol = self.mydb["data"]
        if mycol.find_one({"email":email})!=None:
            x=mycol.delete_one({"email":email})

    def flushHistory(self,email):
        mycol = self.mydb["history"]
        if mycol.find_one({"email": email}) != None:
            mycol.update_one({"email": email}, {"$set": {"log": []}})

    def updateData(self,email,key,value):
        mycol = self.mydb["data"]
        if mycol.find_one({"email": email}) != None:
            mycol.update_one({"email": email}, {"$set": {key:value}})
    
    '''





class AdvisorDatabase:
    def __init__(self):
        self.client = pymongo.MongoClient("mongodb://jd254:pass123@cluster0-shard-00-00-yftzb.mongodb.net:27017,cluster0-shard-00-01-yftzb.mongodb.net:27017,cluster0-shard-00-02-yftzb.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true")
        self.mydb = self.client["advisor"]

    #this gives a dicionary containing all advisors with key as email and password as value
    def getData(self):
        mycol = self.mydb["data"]
        res={}
        for x in mycol.find({},{"email":1,"password":1}):
            res[x["email"]]=x["password"]
        return res



    #returns a dict containing the details of the user whose email is passed as paramater
    def getCompleteInfo(self,email):
        mycol=self.mydb["data"]
        res=mycol.find_one({"email":email},{"_id":0,"password":0})
        if res is None:
            return False
        return res
    def getDataFromEmail(self,email):
        mycol=self.mydb["data"]
        x=mycol.find_one({"email":email},{"_id": 0})
        if x == None:
            return False
        else:
            return x


    '''def insertData(self, name, phoneNumber, email, dateOfBirth,type, gender, password, location=None):
        mycol = self.mydb["data"]
        if mycol.find_one({"email": email}) == None:
            x = mycol.insert_one(
                {"name": name, "phoneNumber": phoneNumber, "email": email, "dateOfBirth": dateOfBirth,"type":type ,"gender": gender,
                 "password": password, "location": location})
            return True
        else:
            return False

    def insertHistory(self, email, time):
        mycol = self.mydb["history"]
        if mycol.find_one({"email": email}) == None:
            x = mycol.insert_one({"email": email, "log": []})
        log = mycol.find_one({"email": email})['log']
        log.insert(0, time)
        mycol.update_one({"email": email}, {"$set": {"log": log}})

    def deleteData(self, email):
        mycol = self.mydb["data"]
        if mycol.find_one({"email": email}) != None:
            x = mycol.delete_one({"email": email})

    def flushHistory(self, email):
        mycol = self.mydb["history"]
        if mycol.find_one({"email": email}) != None:
            mycol.update_one({"email": email}, {"$set": {"log": []}})

    def updateData(self,email,key,value):
        mycol = self.mydb["data"]
        if mycol.find_one({"email": email}) != None:
            mycol.update_one({"email": email}, {"$set": {key:value}})
    '''

EndGame/mainapp/views.py
from django.shortcuts import render
from django.template import loader
from .models import AdvisorDatabase, CustomerDatabase
from django.http import HttpResponseRedirect
from selenium import webdriver
from PIL import Image
# Create your views here.

def index(request):
    if request.COOKIES.get("loggedIn",None):
        db = AdvisorDatabase()
        email=request.COOKIES.get("userName")
        user = db.getDataFromEmail(email)
        return render(request, 'mainapp/home.html', {'user': user})
    return render(request, 'mainapp/login.html', {})

def login(request):
    '''retrieving data from form and validation and redirection to dashboard page'''
    db = AdvisorDatabase()
    dict_of_officials = db.getData()
    uname = request.GET['username']
    psw = request.GET['pass']
    try:
        if dict_of_officials[uname] == psw:
            user = db.getDataFromEmail(uname)
            response=render(request, 'mainapp/home.html', {'user': user})
            response.set_cookie("loggedIn",True)
            response.set_cookie("userName", uname)
            return response
        else:
            return render(request, 'mainapp/index.html', {})
    except Exception as ae:
        ctx = {'ae': ae}
        return render(request, 'mainapp/error.html', ctx)

def dashboard(request):

    '''with open("./mklog.txt","wt") as f:
        f.write(str(request))'''
    if request.COOKIES.get("loggedIn",None):
        db = AdvisorDatabase()
        email=request.COOKIES.get("userName")
        user = db.getDataFromEmail(email)
        return render(request, 'mainapp/home.html', {'user': user})
    else:
        return render(request, 'mainapp/login.html', {})

def logout(request):
    if request.COOKIES.get("loggedIn"):
        response = render(request,'mainapp/login.html',{})
        response.delete_cookie("userName")
        response.delete_cookie("loggedIn")
        return response
    else:
        render(request, 'mainapp/error.html', {})

def myCustomers(request):
    if request.COOKIES.get("loggedIn"):
        db = CustomerDatabase()
        customers= db.getData()[:20]
        return render(request, 'mainapp/customers.html' ,{'customers' : customers})
    else:
        return render(request, 'mainapp/login.html', {})

def customerDetail(request, pk):
    db = CustomerDatabase()
    customer = db.getDataFromPk(int(pk))
    return render(request,'mainapp/showdetails.html',{'customer' : customer})

def searchDetails(request):
    if request.COOKIES.get("loggedIn"):
        return render(request, 'mainapp/searchdetails.html',{})
    else:
        return render(request, 'mainapp/login.html', {})

def sendEmail(request):
    return HttpResponseRedirect("https://mail.google.com/mail/?view=cm&fs=1&to=neotrix1111@gmail.com&su=SUBJECT&body=BODY&bcc=someone.else@example.com")


def grabPhoto(request):
    links = request.GET['photoLinks']
    user = request.GET.get('user')
    links = links.split(",")
    index=0
    driver = webdriver.Chrome(executable_path='D:/chromedriver.exe')
    for link in links[:1]:
        driver.get(link)
        ss = driver.save_screenshot('ss'+str(index)+'.png')
        index+=1
    driver.quit()
    #all photos are stored in mainapp level
    for x in range(index):
        if '/public/' in links[x]:
            img_obj=Image.open('ss'+str(x)+'.png')
            crop_img=img_obj.crop((211, 315, 295, 395))
            crop_img.save('ss'+str(x)+'.png')
        else:
            img_obj = Image.open('ss' + str(x) + '.png')
            crop_img = img_obj.crop((101, 257, 265, 420))
            crop_img.save('ss' + str(x) + '.png')

    di={}
    db=CustomerDatabase()
    img1=db.getImage(user)

    for x in range(index):
        img2 = 'ss' + str(x) + '.png'
        ans = faceVerify(img1,img2)
        if ans is not None:
            di[ans]=links[x]
    di= dict(sorted(di.items(), reverse=True))
    with open("mklog.txt",'wt') as fh:
        fh.write(str(di))
    return render(request,'mainapp/screenShotDone.html',{'di':di})

def getFaceId(path):
    import requests

    # Replace 'KEY_1' with your subscription key as a string
    subscription_key = 'a8304edad2824566a6ed18bd6b6a34b4'
    filename = path

    uri_base = 'https://westcentralus.api.cognitive.microsoft.com'
    # Request headers
    # for locally stored image files use
    # 'Content-Type': 'application/octet-stream'
    headers = {
        'Content-Type': 'application/octet-stream',
        'Ocp-Apim-Subscription-Key': subscription_key,
    }

    params = {
        'returnFaceId': 'true',
        'returnFaceAttributes': 'smile',
    }
    # route to the face api
    path_to_face_api = '/face/v1.0/detect'
    # open jpg file as binary file data for intake by the MCS api
    with open(filename, 'rb') as f:
        img_data = f.read()
    try:

        response = requests.post(uri_base + path_to_face_api,
                                 data=img_data,
                                 headers=headers,
                                 params=params)

        print('Response:')
        # json() is a method from the request library that converts
        # the json reponse to a python friendly data structure
        parsed = response.json()

        # display the image analysis data
        return parsed[0]['faceId']


    except Exception as e:
        print('Error:')
        print(e)
        return None

def faceVerify(im1,im2):
    import requests

    subscription_key = 'a8304edad2824566a6ed18bd6b6a34b4'

    uri_base = 'https://westcentralus.api.cognitive.microsoft.com'

    headers = {
        'Content-Type': 'application/json',
        'Ocp-Apim-Subscription-Key': subscription_key,
    }
    # Request parameters
    # The detection options for MCS Face API check MCS face api
    # documentation for complete list of features available for
    # detection in an image
    # these parameters tell the api I want to detect a face and a smile
    params = {
        'faceid1':getFaceId(im1),
        'faceid2':getFaceId(im2)
    }
    #print(params)
    # route to the face api
    path_to_face_api = '/face/v1.0/verify'
    # open jpg file as binary file data for intake by the MCS api
    import json
    body1=json.dumps(params)
    try:
        # Execute the api call as a POST request.
        # What's happening?: You're sending the data, headers and
        # parameter to the api route & saving the
        # mcs server's response to a variable.
        # Note: mcs face api only returns 1 analysis at time
        response = requests.post(uri_base + path_to_face_api,
                                 headers=headers,
                                 data=body1)

        #print('Response:')
        # json() is a method from the request library that converts
        # the json reponse to a python friendly data structure
        faces=response.json()

        # display the image analysis data
        return faces['confidence']


    except Exception as e:
        print('Error:')
        print(e)
        return None

EndGame/mainapp/templates/mainapp/ad.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Results</title>
	<link rel="stylesheet" href="{% static 'mainapp/results.css' %}" >
</head>
<body>



	<div class="container">
		<h1>RESULTS</h1>
		{% for key,value in di.items %}
		<div class="item">
			<h3 id="content" >Found in this link {{ value }} with {{ key }} probabilty.<a href="{{ value }}">CLICK</a></h3>

		</div>
		{% endfor %}
	</div>

</body>
</html>

EndGame/mainapp/templates/mainapp/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 key error in dict

{{ customer }}
</body>
</html>

EndGame/mainapp/templates/mainapp/index.html
Error in login

EndGame/mainapp/templates/mainapp/login.html
<!doctype html>
<html lang="en" class="no-js">
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,700' rel='stylesheet' type='text/css'>

	<link rel="icon" type="image/png" href="{% static 'mainapp/login form/favicon.ico' %}"/>

	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"> 
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" type="text/css" href="{% static 'mainapp/login form/Login css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'mainapp/login form/Login css/main.css' %}">
  	
	<title>Login | FUTURE GENERALI</title>
</head>
<body>
	<div class="content-wrapper" style="padding: 0px">
		<div class="container-login100" style="background-image: url('../../static/mainapp/login form/bg.jpg');">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
				<form class="login100-form validate-form" method="get" action="{% url 'mainapp:login' %}">
					{% csrf_token %}
					<span class="login100-form-title p-b-49">
						LOGIN
					</span>
					<div style="border-radius:2px; margin-bottom:32px;padding-left: 0px">
						<select name="selLoginWith" id="selLoginWith" class="selectField" style="padding: 18px">
							<option selected="selected" value="UID">User Name</option>
							<option value="EID">Registered Email Address</option>
							<option value="MoNum">Mobile Number</option>
							<option value="PoNum">Policy Number</option>
							<option value="ClientId">Client Id</option>
						</select>
					</div>
					<div class="wrap-input100 validate-input m-b-23" data-validate = "Username is reauired">
						<span class="label-input100">Username</span>
						<input class="input100" type="text" name="username" placeholder="Type your username">
						
					</div>

					<div class="wrap-input100 validate-input" data-validate="Password is required">
						<span class="label-input100">Password</span>
						<input class="input100" type="password" name="pass" placeholder="Type your password">
						
					</div>
					
					<div class="text-right p-t-8 p-b-31">
						<a href="#">
							Forgot password?
						</a>
					</div>
					
					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn" type="submit">
								Login
							</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>

</body>
</html>

EndGame/mainapp/templates/mainapp/screenShotDone.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Results</title>
    <style>
        body{
            background-image: url("../../static/mainapp/bg.jpg");
            background-size: cover;
            background-color: #1b1e21;
        }

        h1{
            font-size: 50px;
            color: ghostwhite;
            text-align: center;
        }
        .result{
            display: block;
            height: 50px;
            line-height: 50px;
            background: rgba(255,255,255,0.7);
            color:black;
            width: 90%;
            margin: auto;
            box-shadow: 1px 1px 4px black;
            padding: 7px;
        }

        a{
            display: inline-block;
            background-color: #007bff;
            color: white;
            width: 15%;
            position: relative;
            float: right;
            text-align: center;
        }
    </style>
</head>

<body>
<h1>R E S U L T S</h1>
    {% if di %}
    {% for key,value in di.items %}
<h2  class="result">Found in {{ value }} with <span style="color:white;">{{ key }}</span> probability<a href="{{ value }}">CLICK</a></h2>
    {% endfor %}
    {% else %}
    <h1>No dict found</h1>
    {% endif %}
</body>

</html>

EndGame/mainapp/templates/mainapp/showdetails.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Customer Details |  FUTURE GENERALI</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'mainapp/show details/showdetails.css' %}">
    <link href="{% static 'mainapp/assets/css/bootstrap.min.css' %}" rel="stylesheet" />
  <link href="{% static 'mainapp/assets/css/paper-dashboard.css' %}" rel="stylesheet" />
  <link href="{% static 'mainapp/assets/demo/demo.css' %}" rel="stylesheet" />
</head>
<body style="background:black;">


	<div class="wrapper ">
    <div class="sidebar" data-color="black" data-active-color="danger">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
    -->
      <div class="logo">
        <a href="https://general.futuregenerali.in/" class="simple-text logo-mini">
          <div class="logo-image-small">
            <img src="{% static 'mainapp/assets/img/logo.png' %}">
          </div>
        </a>
        <a href="https://general.futuregenerali.in/" class="simple-text logo-normal" style="font-size: 16px">
          FUTURE GENERALI
          <!-- <div class="logo-image-big">
            <img src="../assets/img/logo-big.png">
          </div> -->
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li>
            <a href="{% url 'mainapp:dashboard' %}">
              <i class="fa fa-home"></i>
              <p>Home</p>
            </a>
          </li>
          <li>
            <a href="{% url 'mainapp:myCustomers' %}">
              <i class="fa fa-address-book-o"></i>
              <p>Customers</p>
            </a>
        </li>
          <li class="active-pro">
            <a href="{% url 'mainapp:logout' %}">
              <i class="fa fa-at"></i>
              <p>Logout</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" style="padding-top: 15px">Customer Info</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <form>
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <div class="input-group-append">
                  <div class="input-group-text">
						<i class="fa fa-search"></i>
                  </div>
                </div>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link btn-rotate" href="#pablo">
                  <i class="fa fa-user-circle"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Account</span>
                  </p>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <!-- <div class="panel-header panel-header-sm">
  
  
</div> -->
      <div class="content" >
    	<div id="user-profile-2" class="user-profile" style="margin-top: 140px">
			<div class="tab-content no-border padding-24">
				<div id="home" class="tab-pane in active">
					<div class="row">
						<div class="col-xs-12 col-sm-5 center" style="background:lightblue;">
							<span class="profile-picture">
								<img class="editable img-responsive" alt=" Avatar" id="avatar2" src="http://bootdey.com/img/Content/avatar/avatar6.png">
							</span>

							<div class="space space-4"></div>

							<a href="#" class="btn btn-sm btn-block btn-success" style="width: 51%;position: absolute;top: 64%;left: 25%;">
								<i class="ace-icon fa fa-envelope-o bigger-120"></i>
								<span class="bigger-110">Notify via Message</span>
							</a>

							<a href="{% url 'mainapp:sendEmail' %}" class="btn btn-sm btn-block btn-primary" style="width: 51%;position: absolute;top: 72%;left: 25%;">
								<i class="ace-icon fa fa-envelope-o bigger-110"></i>
								<span class="bigger-110">Notify via E-mail</span>
                            </a>
                            <a href="{% url 'mainapp:searchDetails' %}" class="btn btn-sm btn-block btn-primary" style="width: 51%;position: absolute;top: 82%;left: 25%; background:green">
                                    <i class="ace-icon fa fa-envelope-o bigger-110"></i>
                                    <span class="bigger-110" >Search in Social media</span>
                                </a>
						</div><!-- /.col -->

						<div class="col-xs-12 col-sm-7" style="max-width: 47%;background: whitesmoke;border-radius: 15px;">
                            <div>
							<h4 class="blue">
								<span class="middle">Customer Name</span>
							</h4>

							<div class="profile-user-info">
								<div class="profile-info-row">
									<div class="profile-info-name"> Name </div>

									<div class="profile-info-value">
										<span id="uname">{{ customer.name }}</span>
									</div>
								</div>

								<div class="profile-info-row">
									<div class="profile-info-name"> Location </div>

									<div class="profile-info-value">
										<i class="fa fa-map-marker light-orange bigger-110"></i>
										<span>Netherlands</span>
										<span>Amsterdam</span>
									</div>
                                </div>
                                <div class="profile-info-row">
                                    <div class="profile-info-name">Policy Type</div>
                                    <div class="profile-info-value">
                                        <span>Life Insurance</span>
                                    </div>
                                </div>
                                <div class="profile-info-row">
									<div class="profile-info-name"> Joined </div>
									<div class="profile-info-value">
										<span>2010/06/20</span>
									</div>
                                </div>
                                <div class="profile-info-row">
									<div class="profile-info-name"> Maturity Date</div>
									<div class="profile-info-value">
										<span>{{ customer.maturityDate }}</span>
									</div>
								</div>

								<div class="profile-info-row">
									<div class="profile-info-name"> DateOfBirth </div>
									<div class="profile-info-value">
										<span>{{ customer.dob}}</span>
									</div>
								</div>
							</div>
                                <div class="profile-info-row">
                                        <div class="profile-info-name">Type of customer</div>
                                        <div class="profile-info-value">
                                            <span>Premium</span>
                                        </div>
                                    </div>

								<div class="profile-info-row">
									<div class="profile-info-name"> Contact</div>
									<div class="profile-info-value">
										<span>{{ customer.phoneNumber }}</span>
									</div>
                                </div>
                                <div class="profile-info-row">
                                        <div class="profile-info-name">Email</div>
                                        <div class="profile-info-value">
                                            <span id="email">{{ customer.email }}</span>
                                        </div>
                                    </div>

							<div class="hr hr-8 dotted"></div>

							<div class="profile-user-info">
								<div class="profile-info-row">
									<div class="profile-info-name"> Gender </div>

									<div class="profile-info-value">
										<a href="#" target="_blank">{{ customer.gender }}</a>
									</div>
								</div>
                            </div>
                            <div class="profile-info-row">
								<div class="profile-info-name"> Status </div>
								<div class="profile-info-value">
									<label class="switch">
                                        <input type="checkbox"><span class="slider round"></span>
                                    </label>
								</div>
							</div>
                        </div><!-- /.col -->
                        </div>
					</div><!-- /.row -->
				</div><!-- /#home -->
			</div>
	</div>
  </div>

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<script src="{% static 'mainapp/assets/js/core/jquery.min.js' %}"></script>
  <script src="{% static 'mainapp/assets/js/core/popper.min.js' %}"></script>
  <script src="{% static 'mainapp/assets/js/core/bootstrap.min.js' %}"></script>
  <script src="{% static 'mainapp/assets/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
  <script src="{% static 'mainapp/assets/js/paper-dashboard.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'mainapp/assets/demo/demo.js' %}"></script>
      <script src="{% static 'mainapp/searchdetails/search.js' %}"></script>
</body>
</html>